### ISSUE TITLE
Docs for type aliases

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#1106]
Currently if we look at (for example) the `Str` module, it doesn't show docs for the `Str` type alias itself.

It should though!

Ordinarily we should render the contents of the type alias, but there's one situation where we shouldn't show anything: where the type alias includes one or more private tag union literals. For example:

```elm
## This is a string
Str : [ @Str ]
```
...should render as :

```elm
## This is a string
Str
```

Another example:

```elm
## This is a Foo
Foo :
    {
        stuff : I64,
        thing : [ @Str ],
    }
```
...should render as :

```elm
## This is a thing
Foo
```

...because it contains a private tag union literal somewhere in it. (Note that we shouldn't follow aliases when considering this; if the above example had `Str` instead of `[ @Str ]` then we would have instead rendered the entire type! It's only when there's a private tag union *literal* that we hide everything.)

This should render the entire type alias, because it contains no private tag union literals:

```elm
## This is a Foo
Foo :
    {
        stuff : I64,
        thing : [ Str ],
    }
```

**Comment by skyqrose** [comment]
Aliases show in docs now. Here's a random type example:
![Docs for Decode. DecodeError : [TooShort] Error types when decoding a List U8 of utf-8 bytes using a Decoder](https://github.com/user-attachments/assets/6f10eb9f-48b3-4a79-9145-cda90dd4bf34)
Source: https://github.com/roc-lang/roc/blob/b7c2cb084e15a56320e652ad3c77fdb8262bc1a4/crates/compiler/builtins/roc/Decode.roc#L53

Opaque types are shown but without their definitions.

Interestingly, the `Str` type still isn't in the `Str` docs, because it's not actually defined in https://github.com/roc-lang/roc/blob/b7c2cb084e15a56320e652ad3c77fdb8262bc1a4/crates/compiler/builtins/roc/Str.roc

I'm not sure if every case listed above is done as described, but this issue is 3 years old, so if there are cases that should be improved, they should be written up in a new issue.
