### ISSUE TITLE
Panic in alias analysis when code moved from top level into def

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2775]
If I change Hello World to this, alias analysis panics:

```coffee
main =
    x : List *
    x = []

    foo : List Str -> Bool
    foo = List.isEmpty

    y = foo x

    "Hello, World!\n"
```

The error is:

`Error in alias analysis: error in module ModName("UserApp"), function definition FuncName("\t\x00\x00\x00\x00\x00\x00\x00_\xa8\x0c\xbc5\xf4\x81h"), definition of value binding ValueId(5): expected type '((heap_cell, bag<(heap_cell,)>),)', found type '((heap_cell, bag<()>),)'', compiler/gen_llvm/src/llvm/build.rs:4141:19`

However, if I extract the definitions of `foo` and `x` to the top level, it works.

```coffee
x : List *
x = []

foo : List Str -> Bool
foo = List.isEmpty

main =
    y = foo x

    "Hello, World!\n"
```

Both type annotations are necessary to reproduce this.

**Comment by Ivo-Balbaert** [comment]
The following program:

```coffee
app "test"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br" }
    imports [
        pf.Stdout, 
    ]
    provides [main] to pf

x : List Str
x = []

foo : List Str -> Bool
foo = List.isEmpty

main =
    y = foo x

    Stdout.line "Hello, World!\n"
```

works fine, as well as the same program with the top level defs in main:

```coffee
main =
    x : List Str
    x = []

    foo : List Str -> Bool
    foo = List.isEmpty

    y = foo x

    Stdout.line "Hello, World!\n"
```

In order to be able to compile I had to change x : List * to x : List Str.
With x : List * a  ── TYPE MISMATCH ────────────────────────────────────────────────── test15.roc ─

This 1st argument to foo has an unexpected type:

15│      y = foo x
                 ^

This x value is a:

    List *

But foo needs its 1st argument to be:

    List Str

Tip: The type annotation uses the type variable * to say that this
definition can produce any type of value. But in the body I see that
it will only produce a Str value of a single specific type. Maybe
change the type annotation to be more specific? Maybe change the code
to be more general?

is generated, which seems appropriate.

So I think this issue is solved. @Anton-4 ?
```

**Comment by lukewilliamboswell** [comment]
```
app "test"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br",
    }
    imports [
        pf.Stdout,
    ]
    provides [main] to pf

main = 

    x : List *
    x = []

    foo : List Str -> Bool
    foo = List.isEmpty

    y = foo x

    Stdout.line "Hello, World!\n"
```

```
% roc dev test.roc

── TYPE MISMATCH ──────────────────────────────────────────────────── test.roc ─

This 1st argument to foo has an unexpected type:

18│      y = foo x
                 ^

This x value is a:

    List *

But foo needs its 1st argument to be:

    List Str

Tip: The type annotation uses the type variable * to say that this
definition can produce any type of value. But in the body I see that
it will only produce a Str value of a single specific type. Maybe
change the type annotation to be more specific? Maybe change the code
to be more general?

────────────────────────────────────────────────────────────────────────────────

1 error and 1 warning found in 17 ms.

You can run the program anyway with roc run test.roc
```
