### ISSUE TITLE
Compiler crash if two defs have the same name

### ISSUE THREAD

**Issue by jared-cone** [roc-lang/roc#2865]
On `d23d5f249` modifying `echo.roc` from the examples:

```
app "echo"
    packages { pf: "cli-platform" }
    imports [ pf.Task ]
    provides [ main ] to pf
    
main =
    test = 1
    test = 2
    Task.succeed {}
```

```
thread '<unnamed>' panicked at 'not yet implemented', compiler/mono/src/ir.rs:5654:31
```

Slightly different error if the def is in a conditional:

```
app "echo"
    packages { pf: "cli-platform" }
    imports [ pf.Task ]
    provides [ main ] to pf
    
main =
    str =
        if True then
            test = 1
            ""
        else
            ""
    test = 2
    Task.succeed {}
```

```
thread '<unnamed>' panicked at 'explicit panic', compiler/mono/src/ir.rs:3332:29
```

**Comment by Ivo-Balbaert** [comment]
The 1st code snippet now gives the right error:
── DUPLICATE NAME ─────────────────────────────────────────────────── test.roc ─

The test name is first defined here:

7│      test = 1
        ^^^^

But then it's defined a second time here:

8│      test = 2
        ^^^^

Since these variables have the same name, it's easy to use the wrong
one by accident. Give one of them a new name.

────────────────────────────────────────────────────────────────────
and an equally good error message for code snippet 2:

── DUPLICATE NAME ─────────────────────────────────────────────────── test.roc ─

The test name is first defined here:

13│      test = 2
         ^^^^

But then it's defined a second time here:

9│              test = 1
                ^^^^

Since these variables have the same name, it's easy to use the wrong
one by accident. Give one of them a new name.

So I think this issue can be closed. @Anton-4 ?
