### ISSUE TITLE
Pass `roc_dealloc` a size argument

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#2871]
We should pass `roc_dealloc` a size and then alignment (in that order, just like the order we use for `roc_alloc`).

This way, we can use Rust's [`alloc::dealloc`](https://doc.rust-lang.org/std/alloc/fn.dealloc.html) to implement `roc_dealloc`, which is useful in wasm (currently we just leak memory there because we can't use `alloc::dealloc`) as well as in bindgen.

Also, if I'm using an arena allocation strategy in my host, and a request comes in from the application to deallocate something, I could check to see if that happens to be the allocation at the very end of the bump arena; if it does happen to be, then I can actually free the memory by moving the pointer back.

**Comment by bhansconnect** [comment]
Oh, so this actually has a worse problem for seamless slices. It isn't just about "self-promoting". It is about freeing seamless slices in general:

```coffee
a = List.repeat 7 7  # allocate A
b = List.dropFirst a # b is a slice of a. It increments the refcount.
# a goes out of scope and decrements the refcount
...
# b goes out of scope, decrements the refcount and needs to free a
# if b needs to know the full capacity of a, we have a problem. It doesn't know.
# no way to free a.
```

**Comment by bhansconnect** [comment]
Yeah, I think we should avoid this feature and let someone wanting to use rusts allocator do this: `https://shift.click/blog/on-dealloc/` Though with only needing to cache the size, not the layout. Will just add an extra max(8, alignment) bytes to each allocation. Otherwise, I think we would need to do this under the hood in roc. Which would add the cost all the time even when it isn't needed. This will only add the cost in the case it is needed for rust. @rtfeldman thoughts?

**Comment by rtfeldman** [comment]
Aha, that's a clever solution! Seems like the way to go. 👍
