### ISSUE TITLE
Compiler hangs if two interfaces try to import each other

### ISSUE THREAD

**Issue by jared-cone** [roc-lang/roc#2872]
On `d23d5f249`

```
interface Test1
    exposes [
    ]
    imports [
        Test2
    ]
```

```
interface Test2
    exposes [
    ]
    imports [
        Test1
    ]
```

No crash or output from the compiler, just stalls until killed.

**Comment by Ivo-Balbaert** [comment]
This situation now gives a very neat error message:

── IMPORT CYCLE ─────────────────────────────────────────────── Interface2.roc

I can't compile Interface2 because it depends on itself through the
following chain of module imports:

    ┌─────┐
    │     Interface2
    │     ↓
    │     Interface1
    │     ↓
    │     Interface2
    └─────┘

Cyclic dependencies are not allowed in Roc! Can you restructure a
module in this import chain so that it doesn't have to depend on
itself?
-------------------------------------------------------------------------------------------------------------

So I think this issue is solved and can be closed. @Anton-4 ?
