### ISSUE TITLE
Parse errors insert ANSI colors instead of HTML colors in the Web REPL

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#3297]
Trying `\x -> when x` on the web REPL yields:

```
» \x -> when x is
[36m── MISSING EXPRESSION ──────────────────────────────────────────────────────────[0m

I am partway through parsing a definition, but I got stuck here:

[36m4[0m[36m│[0m  [37m    \x -> when x is[0m
                       [31m^[0m

I was expecting to see an expression like [33m42[0m or [33m"hello"[0m.
```

My guess is that since parse errors are handled elsewhere than type errors, the escape codes aren't removed properly.

**Comment by snprajwal** [comment]
It looks like these are the lines causing the issue, the ANSI palette is hardcoded in here

https://github.com/roc-lang/roc/blob/04bceae9561881efec97be285f43c1a71dda9f42/crates/reporting/src/error/expect.rs#L159
https://github.com/roc-lang/roc/blob/04bceae9561881efec97be285f43c1a71dda9f42/crates/reporting/src/error/expect.rs#L199

This needs to somehow be refactored so that it uses a different palette based on whether the REPL is invoked in the CLI or browser

**Comment by brian-carroll** [comment]
Thanks @snprajwal !
Here's the line where the Wasm REPL passes down which palette it wants to use
https://github.com/roc-lang/roc/blob/07ceabc9aa12c81792c33b98f7e45b9d05f903ca/crates/repl_wasm/src/repl.rs#L178
And here's the equivalent line for the CLI REPL
https://github.com/roc-lang/roc/blob/07ceabc9aa12c81792c33b98f7e45b9d05f903ca/crates/repl_cli/src/lib.rs#L340
