### ISSUE TITLE
No compile error for invalid use of `?` in destructure

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3683]
To reproduce:

```elm
fn : { x : Str } -> Str
fn = \{ x ? ""} -> x
```
This should report an error, because it's using a non-optional record field as an optional one. However, it does not!

**Comment by Ivo-Balbaert** [comment]
This program:

fn : { x : Str } -> Str
fn = \{ x ? ""} -> x

main =
    Stdout.line "Hello, World!\n"

now returns an error:

── TYPE MISMATCH ────────────────────────────────────────────────── test16.roc ─

The 1st argument to fn is weird:

9│  fn = \{ x ? ""} -> x
          ^^^^^^^^^

The argument is a pattern that matches record values of type:

    { x ? Str }

But the annotation on fn says the 1st argument should be:

    { x : Str }

────────────────────────────────────────────────────

I think this issue is solved. @Anton-4 ?

**Comment by lukewilliamboswell** [comment]
```
app "test"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.4.0/DI4lqn7LIZs8ZrCDUgLK-tHHpQmxGF1ZrlevRKq5LXk.tar.br",
    }
    imports [
        pf.Stdout,
    ]
    provides [main] to pf

main = Stdout.line "foo"

fn : { x : Str } -> Str
fn = \{ x ? ""} -> x
```

```
% roc dev test.roc

── TYPE MISMATCH ──────────────────────────────────────────────────── test.roc ─

The 1st argument to fn is weird:

13│  fn = \{ x ? ""} -> x
           ^^^^^^^^^

The argument is a pattern that matches record values of type:

    { x ? Str }

But the annotation on fn says the 1st argument should be:

    { x : Str }

────────────────────────────────────────────────────────────────────────────────

1 error and 1 warning found in 17 ms.

You can run the program anyway with roc run test.roc
```
