### ISSUE TITLE
TUTORIAL.md snippets should be tested in CI

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#4103]
The difficulty here is to avoid duplication of the snippets. Perhaps we should try to build the TUTORIAL.md file using a different file format where we have references to roc files for the snippets instead of the literal code.

**Comment by rtfeldman** [comment]
I like that idea!

I think more specifically what we should probably do is to:
- Generate a HTML tutorial from the current `TUTORIAL.md` and host it on roc-lang.org
- Change how we generate that HTML to use Roc file snippets for the examples instead of one big `.md` file
- Run tests on the snippets to make sure they still compile

**Comment by Anton-4** [comment]
This issue is a bit outdated, I've created a new one in #6329.
