### ISSUE TITLE
importing defined-but-not-exposed symbol crashes debug compiler

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#4148]
```
# A.roc
interface A exposes [] imports []

foo = ""
```

```
# B.roc
interface B exposes [] imports [A.{foo}]

bar = foo
```

Checking `B.roc` hits a debug_assertion. We should fix that.

**Comment by Ivo-Balbaert** [comment]
With the code as given above, roc check B.roc gives the correct error:


── UNRECOGNIZED NAME ─────────────────────────────────────────────────── B.roc ─

The A module does not expose anything by the name foo.

─────────────────────────────────────────────────────
1 error and 2 warnings found in 21 ms.

When A.roc is changed to: 
interface A exposes [foo] imports []

foo = ""

roc check gives an UNUSED DEFINITION and
0 errors and 1 warning found in 20 ms.

So it seems this issue is fixed?  @Anton-4 ?
