### ISSUE TITLE
List pattern matching

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#4171]
It would be quite useful to be able to use pattern matching on lists:

```coffee
when Str.split input " " is
    [cmd, num] -> doProblem cmd num
    _ -> StdErr.line "faild to split input: \(input)"
```

**Comment by ayazhafiz** [comment]
We should think about what exactly pattern matching lists should support. Namely, should Roc support pattern matching rest-patterns in lists? E.g.

```
when Str.split input " " is
    [cmd, num, ..] -> doProblem cmd num
    _ -> StdErr.line "faild to split input: \(input)"
```

where the first branch would match any list of length 2 or more. I think we should for ergonomic reasons.

If we go down this route, it's important that we model the branch compiler correctly to produce efficient decision trees. I think you need to model lists as cons-lists (where `..` is a `_` pattern) in the decision tree compiler so that if you have two branches

```
when l is
  [a, b, c, ..] ->
  [a, b, ..] ->
```

The second branch could actually be treated as a sub-case of the first one.

**Comment by ayazhafiz** [comment]
This is a larger project, going to mark it as such.
