### ISSUE TITLE
Don't render stay question marks in types

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#4432]
https://github.com/roc-lang/roc/pull/4427#discussion_r1008515590 demonstrates this - the error message in question has random question marks in the types.

I don't know where they came from, but they shouldn't be there! 😄

**Comment by ayazhafiz** [comment]
This is fixed in the OIOP PR
________________________________
From: Richard Feldman ***@***.***>
Sent: Saturday, October 29, 2022 4:37:58 AM
To: roc-lang/roc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [roc-lang/roc] Don't render stay question marks in types (Issue #4432)


#4427 (comment)<https://github.com/roc-lang/roc/pull/4427#discussion_r1008515590> demonstrates this - the error message in question has random question marks in the types.

I don't know where they came from, but they shouldn't be there! 😄

**Comment by ayazhafiz** [comment]
Fixed by the OIOP PR
