### ISSUE TITLE
Reporting of mismatched records lists no mismatched fields

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#5316]
```
app "test" provides [main] to "./platform"

main =
    isCorrectOrder { left: IsList [IsStr ""], right: IsList [IsStr ""] }
#   ^^^^^^^^^^^^^^

isCorrectOrder = \pair ->
#^^^^^^^^^^^^^^{-1}
    when pair is
        { left: IsStr left, right: IsStr right } -> left < right
        { left: IsList l, right: IsList r } ->
            if List.map2 l r (\left, right -> { left, right }) |> List.all isCorrectOrder then
                List.len l < List.len r
            else
                Bool.false

        { left: IsList _, right: IsStr _ } -> isCorrectOrder { left: pair.left, right: IsList [pair.right] }
        { left: IsStr _, right: IsList _ } -> isCorrectOrder { left: IsList [pair.left], right: pair.right }
```

produces

```
Type problems: ── TYPE MISMATCH ──────────────────────────────────────────────────── test.roc ─

This 1st argument to `isCorrectOrder` has an unexpected type:

4│      isCorrectOrder { left: IsList [IsStr ""], right: IsList [IsStr ""] }
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The argument is a record of type:

    { … }

But `isCorrectOrder` needs its 1st argument to be:

    { … }

```

This shouldn't give an empty diff!

**Comment by Ivo-Balbaert** [comment]
Running this program now shows filled in values for the types in the error:

── TYPE MISMATCH ────────────────────────────────────────────────── test24.roc ─

This 1st argument to isCorrectOrder has an unexpected type:

9│      isCorrectOrder { left: IsList [IsStr ""], right: IsList [IsStr ""] }
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The argument is a record of type:

    {
        left : [
            IsList (List [
                IsList (List [
                    IsList ∞,
                    IsStr (Num a),
                ] as ∞),
                IsStr Str,
            ]),
            IsStr (Num a),
        ],
        right : [
            IsList (List [
                IsList (List [
                    IsList ∞,
                    IsStr (Num a),
                ] as ∞),
                IsStr Str,
            ]),
            IsStr (Num a),
        ],
    }

But isCorrectOrder needs its 1st argument to be:

    {
        left : [
            IsList (List a),
            IsStr (Num a),
        ] as a,
        right : [
            IsList (List b),
            IsStr (Num a),
        ] as b,
    }

──────────────────────────────────────────────────────

I can't verify whether these are the correct types, but if so then this issue is solved I think. @Anton-4 ?
