### ISSUE TITLE
intel mac `nix profile install github:roc-lang/roc` failure

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#5358]
Originally posted [here](https://github.com/roc-lang/roc/issues/5183#issuecomment-1531106214) by @PlumpMath:
"
I cannot install Roc using 'nix profile install github:roc-lang/roc' on my Mac with an Intel processor. It has only worked on NixOS and Mac M2 since I first wrote this post. (Currently, even my Zig-related tests are not running)
"

**Comment by Anton-4** [comment]
Can you share the error message that was shown when you ran `nix profile install github:roc-lang/roc` @PlumpMath?

**Comment by PlumpMath** [comment]
Mac intel `cargo build --release --bin roc`
https://github.com/roc-lang/roc/issues/5357#issuecomment-1531960805

**Comment by PlumpMath** [comment]
`nix profile install github:roc-lang/roc`

log is...

**Comment by PlumpMath** [comment]
I just ran 'nix-shell' in the roc directory 
and 
then successfully ran 'cargo build --release --bin roc', obtaining 'target/release/roc'

Thanks!

I was able to run 'cargo build' after running 'nix-shell' on a Mac M2 with an ARM processor, 
and 
solve! run 'rocLovesZig.roc' from 'examples/platform-switching/' using the resulting 'target/release/roc' file. 
Currently, it is also running (compiling) on a Mac Intel (success too). 

I do not plan to install it using nix profile, as it does not include the 'nix-shell' part because your hint `cargo build --release --bin roc`.

I tried to make it work by referring to your 'flake.nix' file and declaring the necessary environment variables, 
but globally declaring other environment variables besides 'buildInputs' caused more problems.

**Comment by Anton-4** [comment]
I now see that `nix profile install github:roc-lang/roc` tries to use the flake.nix to build a binary whereas we currently only support using a devShell with the flake.nix file.

`nix profile install github:roc-lang/roc` will work when #5361 is done, so I will close this as a duplicate.

I'm glad it's working for you now @PlumpMath!

> Anyway, as I briefly mentioned yesterday, I think the roc-lang project is like a battle between humans and machines in the age of AI. Haha. I hope this project succeeds and eliminates the class divide between corporate developers and individual developers, unifying many languages under roc-lang.

We do indeed want roc to be a language for all kinds of developers and make roc work well with other languages :)
