### ISSUE TITLE
Pipes ignore parenthesis wrapping an application

### ISSUE THREAD

**Issue by agu-z** [roc-lang/roc#5379]
`x |> (fn y)` currently desugars to `fn x y`, as if `(fn y)` was not wrapped in parenthesis.

The presence of parenthesis means that `(fn y)` should be applied first, and the resulting function should then be applied with `x`.

In other words, it should desugar to `(fn y) x`, allowing us to pipe to manually-curried functions.

**Comment by rtfeldman** [comment]
I think this is because when https://github.com/roc-lang/roc/blob/ec21f1982611915bfbfffb4b89eece4cdc043ebd/crates/compiler/can/src/operator.rs#L31 runs, parens have already been removed by a previous desugaring step.

One idea for how to deal with this: don't desugar parens yet; rather, drop them in canonicalization (in other words, [this branch](https://github.com/roc-lang/roc/blob/ec21f1982611915bfbfffb4b89eece4cdc043ebd/crates/compiler/can/src/expr.rs#L1378) would actually get taken instead of being an `internal_error!`).

I'm not sure what the implications of this would be, but off the top of my head I can't think of any problems it would cause.

**Comment by wontem** [comment]
A snippet to reproduce

```
minus = \x, y ->
    x - y

(
    (2 |> minus 3),
    (2 |> (minus 3))
) == (-1, 1)
```

Please assign the issue to me

**Comment by Anton-4** [comment]
Done :)

**Comment by rtfeldman** [comment]
Panic as in having the compiler panic? Or something else? 😄

**Comment by wontem** [comment]
I mean syntax error. The log above is from roc repl

**Comment by rtfeldman** [comment]
Ah, yes! Indeed, this should be a compiler error—and specifically "too few args" is the correct error! 🎉
