### ISSUE TITLE
Docker Hub official image

### ISSUE THREAD

**Issue by khalyomede** [roc-lang/roc#6045]
Hello, I know this is a little early, but I am sure some folks would love to have ready-to-go images to play with Roc (without surprise, I would include myself into this group).

I can also create a repository under my namespace, if the team is not eager to maintain a Docker image (which I can totally understand in regard to all the remaining work).

I can see 2 tags for the image:

- `ubuntu-2204-nightly`
- `alpine-3-nightly`

> [os]-[os-major-version]-[roc-version]

Not sure if tagging minor OS version makes sense at this point.

The most basic image for demonstration purpose:

```dockerfile
FROM ubuntu:22.04

RUN apt-get update --fix-missing
RUN apt-get upgrade --yes
RUN apt-get install --yes \
    wget \
    libc-dev \
    binutils \
    build-essential \
    clang
RUN wget -q -O roc.tar.gz https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz
RUN mkdir /usr/lib/roc
# --strip-components=1 not needed once https://github.com/roc-lang/roc/issues/4118 is solved.
RUN tar -xvz -f roc.tar.gz --directory /usr/lib/roc --strip-components=1

ENV PATH="$PATH:/usr/lib/roc"
```

N.B.: probably not the correct repo, if the idea is well received the team may create the docker repository under the roc-lang namespace. 

Being part of the namespace would allow to automatize building the Docker images once a new version (nightly) comes out.

**Comment by aminnairi** [comment]
It would be great to create a user with the permissions `1000:1000` as per the Node.js official Docker image to ease the permission handling of this image through a container when run in case it has to create/read/delete files since running a container as `root` can be an issue, especially for folks running on Linux or Mac (can't say that for Windows as I have never used Docker on Windows).

```dockerfile
FROM archlinux:latest

ARG USER_ID=1000
ARG GROUP_ID=1000

USER root

WORKDIR /root

RUN pacman -Syy --noconfirm wget tar gzip \
  && groupadd --gid $GROUP_ID roc \
  && useradd --uid $USER_ID --gid $GROUP_ID --create-home --shell /bin/sh roc \
  && wget -q -O roc.tar.gz https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz \
  && mkdir --parent /usr/local/lib/roc \
  && tar -xvz -f roc.tar.gz --directory /usr/local/lib/roc --strip-components=1

ENV PATH="$PATH:/usr/local/lib/roc"

USER roc

WORKDIR /home/roc
```

Not sure why I'm getting a `Can't find module Os` when running the repl inside the container but it works as expected with the correct permissions.

Using Archlinux here, but it could easily be swapped out for Debian or Alpine, although from the tests, alpine seems to be not working as for Archlinux, I'm suspecting a missing dynamic library for roc to run just [like I did for Elm](https://github.com/aminnairi/elm-docker/blob/latest/Dockerfile) some years ago.

**Comment by Anton-4** [comment]
Hi @khalyomede,
I've already claimed the roclang username on dockerhub (roc-lang was not allowed).
Someone on zulip was also interested in a docker image.

If someone would be willing to make a PR to the roc repo with a Dockerfile and tests (github workflow) I'll set up nightlies with dockerhub. The tests at the end of [this script](https://github.com/roc-lang/roc/blob/main/ci/basic_nightly_test.sh) should be used.

**Comment by ageron** [comment]
The official docker images are available at: https://hub.docker.com/u/roclang
