### ISSUE TITLE
Will Roc ever support Haskell style function definions?

### ISSUE THREAD

**Issue by jumpinggoofballs** [roc-lang/roc#6065]
I have only recently learnt about Roc, and I am very excited about what it promises. But given its emphasis on ergonomics, some of the design choices made are a bit odd. 

For example, the way functions are defined. There is currently exactly one syntax for defining a funcion:
```
myFun = \x, y -> ...
```

Is there any _good_ reason for why we should not be able to write:
```
myFun x y = ...
```
like in Haskell? 

Also, while I am here: what is the reason for why currying is not supported? Is it something to do with performance, or complete type inference?

Thanks, and wish you the very best with this project!

**Comment by lukewilliamboswell** [comment]
This was discussed and answered recently on zulip https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/.5C.20for.20lambdas.3A.20was.20that.20strictly.20necessary.3F/near/403250028

And for currying see FAQ answer here https://github.com/roc-lang/roc/blob/main/FAQ.md#why-arent-roc-functions-curried-by-default

**Comment by lukewilliamboswell** [comment]
Good idea. I was on my phone earlier, but happy to do that.

@joshuawarner32 said in [Zulip thread](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/.5C.20for.20lambdas.3A.20was.20that.20strictly.20necessary.3F/near/403250028)

Particularly with multiple arguments, or when using pattern matching in arguments, that will make parsing much more difficult (maybe impossible to parse unambiguously).

Even ignoring the difficulty of parsing, in practice I think this will lead to needing to put parens around the lambda in order to clear up the ambiguity.

There are a couple cases. You can do pattern matching / destructuring in the arguments to a lambda - e.g. `\Foo a b -> a+b` - which both destructures a Foo tag, pulls out the two fields, and then binds those as variables in the body.

Right now you can pass that lambda as an argument to a function like so: `myFunc \Foo a b -> a+b`. Without the `\`, that becomes: `myFunc Foo a b -> a+b`. Is that a function call taking a closure as it's only argument? Or is that a function taking the tag `Foo`, the value `a`, and a single-argument closure `b->a+b` as arguments?

In order to make that unambiguous, you'd have to add parens like so: `myFunc (Foo a b -> a+b)`

The other case is around lambdas accepting multiple arguments - e.g. `\a, b -> a+b`.
This works fine in the context above (passing it as an argument) - but we run into trouble if we have to put that  _anywhere inside_ parenthesis.

e.g. `(a, b -> a+b)` becomes ambiguous whether you mean a tuple with two fields `a` and `b -> a+b`, or a parenthesized lambda that takes two arguments. Note that this is true if it's nested anywhere, even deeply inside a parenthesized expression (or a list with `[]` - same thing).

Also note that there's a closely-related problem around "multi-backpassing" - e.g. `a, b <- foo`, that's been discussed before. That doesn't use an introducer like `\`, and so has same problems as above.

Currently we resolve this ambiguity by saying you can't ever use multi-backpassing anywhere inside a parenthesized expression - and that's mostly fine because needing multiple "return values" (which are really arguments) is rare.

I don't think it would fly if we made the same restriction on lambdas, particularly given that you're going to have to parenthesize them in some new cases you didn't before (see the first point).

**Comment by joshuawarner32** [comment]
I actually think this issue is a bit different from the question I was responding to in Zulip (or maybe I misunderstood that one?).

> Is there any good reason for why we should not be able to write:
> myFun x y = ...

This would likely be a @rtfeldman question - that decision is before my time. I _can_ say that the parser has code in it that detects if you try to define a function like that and gives a helpful error message. My speculation would be that defining functions like `myFun = \x, y ->` makes that the same as defining a closure/lambda - which is a nice educational two-for-one, particularly for folks not coming from a functional background.

> Also, while I am here: what is the reason for why currying is not supported?

There's a section here documenting the reason behind this: https://github.com/roc-lang/roc/blob/main/FAQ.md#why-arent-roc-functions-curried-by-default
