### ISSUE TITLE
Support embedding parts of a roc-file with the static-site-gen platform

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6328]
Currently the static-site-gen supports embedding Roc files in markdown like this:
```roc
file:main.roc
```

It's very useful to only show a section of a Roc file,  so we should add:
```roc
file:main.roc:snippet:hello
```

In the Roc file you'd have comments like this to indicate the start and end of the snippet:
```
app "hello-world"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.1/Icc3xJoIixF3hCcfXrDwLCu4wQHtNdPyoJkEbkgIElA.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

### start snippet hello
main = Stdout.line "Hello, World!"
### end snippet
```

Changes should be made [here](https://github.com/roc-lang/roc/blob/901e771424b38fa10b0d76f0a60baee863517686/examples/static-site-gen/platform/src/lib.rs#L368).

This feature would be very valuable because it would allow us to check all tutorial snippets for errors by doing  `roc check` on the Roc files (#6329).

**Comment by isaacvando** [comment]
Could the syntax for referencing a snipped be `file:main.roc:hello` instead?

**Comment by Anton-4** [comment]
Hmm, the addition of `snippet` does make it clear we're not referring to a function named `hello`.
It also seems like the cost of verbosity is quite low, it's not like with a variable name for example.
I'd like to try it out with `snippet` for now.

**Comment by michaelkpfeifer** [comment]
The Roc formatter replaces
```
### start snippet hello
```
by
```
# ## start snipped hello
````
which means that every file using this feature is formatted incorrectly. (Compare failed test run https://github.com/roc-lang/roc/actions/runs/7562066467/job/20699431954.)

Assuming that there are good reasons why the Roc formatter replaces `###`  by `# ##` (and `#--` by `# --`) , a simple way to solve this is to use `##`  instead of `###` . But this will probably lead to other problems since `##` seems to be used for documentation purposes. 

I feel that `# ##` is not ideal since people would probably wonder why there is an additional space character. Maybe `# --` ?
