### ISSUE TITLE
Unexpected Results from List.prepend

### ISSUE THREAD

**Issue by michaelkpfeifer** [roc-lang/roc#6343]
`List.prepend` returns unexpected results. The following code fragment contains three tests.
```
interface EIR exposes [] imports []

expect
       List.prepend [2] 1 == [1, 2]

expect
    payment1 : { amount: Dec, date: [RD I32] }
    payment1 = { amount: 1dec, date: (RD 1000) }
    payment2 : { amount: Dec, date: [RD I32] }
    payment2 = { amount: 2dec, date: (RD 1001) }
    both = [payment1, payment2]
    List.prepend [payment2] payment1 == both

expect
    payment1 : { amount: Dec, date: [RD Dec] }
    payment1 = { amount: 1dec, date: (RD 1000) }
    payment2 : { amount: Dec, date: [RD Dec] }
    payment2 = { amount: 2dec, date: (RD 1001) }
    both = [payment1, payment2]
    List.prepend [payment2] payment1 == both
```
The first very simple test succeeds. The second one fails. `List.prepend` returns something like
```
[{ amount: 1, date: RD 1000 }, { amount: 18465.190817783261167616, date: RD 797499858 }]
```
The third test succeeds. The differences between the second test and the third test are the two type annotations. `I32`instead of `Dec`. 

Tested with a nightly build and with a binary compiled from scratch around Dec 31, 2023.

Similar results are produced by `List.concat`.

**Comment by folkertdev** [comment]
so, it turns out this bug is kind of nasty. Really it is because LLVM, our main code generation backend, considers `Dec` to have an alignment of 8, not 16. (16 makes more sense). LLVM will change this in an upcoming version.

https://github.com/roc-lang/roc/pull/6462 does fix some logic issues around `List.prepend`. So this example will now work in the repl, for instance. 

but really I don't see a much better solution than waiting for an LLVM version where this is fixed...

**Comment by michaelkpfeifer** [comment]
Thank you for looking into this issue and for the explanation. At least, I know now that I have to wait for an LLVM fix. In the meantime, I will find some workaround.

**Comment by JRI98** [comment]
No longer reproduces
