### ISSUE TITLE
Change basic-cli link on www.roc-lang.org/docs to point to latest basic-cli release 

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6796]
I'll add this to the basic-cli release workflow.

**Comment by skyqrose** [comment]
Not resolved by the above PR because versions have increased since then. [Currently points](https://github.com/roc-lang/roc/blob/22423ca98bef41e2f55ae54e11c632bd0610c241/www/content/docs.md#L5) to 0.15.0, but the latest basic-cli release is [0.16.0](https://www.roc-lang.org/packages/basic-cli/0.16.0)

When you say "add to the basic-cli release workflow", do you mean a github actions workflow, or does basic-cli have documentation about how to do a release where this should get added as a checklist item?

**Comment by Anton-4** [comment]
After some thought this seems to be the best solution: https://github.com/roc-lang/basic-cli/issues/273
