### ISSUE TITLE
Add syntax sugar that translates ? to Result.try

### ISSUE THREAD

**Issue by smores56** [roc-lang/roc#6828]
Issue following from discussion in [Zulip chat](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/early.20return.20operator.20for.20Result/near/445985059).

We want to add Rust's try operator, the `?`, to Roc, making early returns on `Err` cleaner. This will work just like `!` works when it desugars to `Task.await`.

There are many benefits to having `?` added to Roc, including "flatter" code, better readability, and better concision, but these could also be achieved if ! was extended to work for `Result`s or even anything implementing a hypothetical `AndThen` ability. However, the mental overhead of understanding that a return type's `AndThen` implementation is being leveraged, as well as the teach-ability damage to the language, make generalizing the ! operator cost-prohibitive. By having `!` *just* for `Task`s and `?` *just* for `Result`s, we get the cleanliness benefits of each operator without making the language much harder to learn, and we prevent potential exploitation of a generalized `!` operator.

This also paves the way for the eventual deprecation and removal of backpassing from the language.

Some things we should consider when implementing this operator:

- It will work almost exactly like the `!` operator, but will instead translate to `Result.try` every time
- The error messages we generate on type errors will not only need to handle when the value `?` is used on isn't a tag union, but also if there are extra or missing variants from `[Ok _, Err _]`

**Comment by sekerez** [comment]
Would love to have a go at this! Looking into it, will provide an update

**Comment by lukewilliamboswell** [comment]
I can give you some good pointers on this. 

First step is to implement a new variant in `crates/compiler/parse/src/ast.rs`, probably something like `ResultTryQuestion` or something, that is almost identical to [TaskAwaitBang(&'a Expr<'a>)](https://github.com/roc-lang/roc/blob/f8c6786502bc253ab202a55e2bccdcc693e549c8/crates/compiler/parse/src/ast.rs#L426).

You should add some snapshot tests in `crates/compiler/test_syntax/tests/snapshots/pass` and confirm it parses correctly. 

 That is probably one PR.

Then the next step is to desugar it, which I've nicknamed "unwrap" because the best place I think to do this is directly after all the Expr's get desugared but before the rest of canonicalisation. Specifically, in `crates/compiler/can/src/suffixed.rs`, you will find [the unwrap_suffixed_expression](https://github.com/roc-lang/roc/blob/f8c6786502bc253ab202a55e2bccdcc693e549c8/crates/compiler/can/src/suffixed.rs#L89) which is responsible for desugaring the `!` operator. So we can modify this to also handle the `?` suffix. You can find the tests for this in `crates/compiler/can/tests/test_suffixed.rs`

If you need any assistance with parsing @joshuawarner32 is definitely the expert. For more general things @kdziamura and myself have been working in this part of the compiler recently. Hope this helps. 😍

**Comment by sekerez** [comment]
Thanks @lukewilliamboswell
