### ISSUE TITLE
Formatter deletes comments between annotation and body

### ISSUE THREAD

**Issue by kdziamura** [roc-lang/roc#6896]
Roc formatter deletes comments that are between annotation and body

Repro:

`Bug.roc`
```roc
app [main] {
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br",
}

import pf.Task exposing [Task]

main =
    x : U64
    # comment
    x = 42

    Task.ok x
```

`roc format Bug.roc`

## Actual

```roc
app [main] {
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br",
}

import pf.Task exposing [Task]

main =
    x : U64
    x = 42

    Task.ok x
```

## Expected

Comments are preserved

**Comment by a-lavis** [comment]
I started looking into this issue - here's what I've found so far:

Reverting cc7d3d3e1dfaeb79555e613acf13bad6e69aa4c8 fixes this bug.  Before cc7d3d3e1dfaeb79555e613acf13bad6e69aa4c8, the compiler didn't accept when there were multiple newlines between a type annotation and body.  After cc7d3d3e1dfaeb79555e613acf13bad6e69aa4c8 it does, but it only records the first part of whatever is between the annotation and body into the AST:
https://github.com/roc-lang/roc/blob/d5db3137a3d8da46f92c31b6bf088bc495f759c2/crates/compiler/parse/src/expr.rs#L1278-L1280

In the above case, the contents of `spaces_before_current` would be:
```
[
    Newline,
    LineComment(
        " comment",
    ),
]
```
Because we're only taking the first thing from `spaces_before_current` (`Newline`, but not the `" comment"` from the `LineComment`), the AST doesn't contain any information about the comment.
I think we need to store all of the information from `spaces_before_current` inside the created `ValueDef::AnnotatedBody`'s `comment`, not just the first element.
