### ISSUE TITLE
Format invisible unicode as a literal

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#6927]
Have the formatter swap invisible unicode in Str with the literal

See [zulip discussion for more context](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Non-printable.20characters.20in.20.60Str.60/near/454529871)

## example module
```roc
module []

# this string has invisible unicode in it... let's have the formatter make this obvious
stringWithInivisbleUnicode = "﻿FOO"

expect stringWithInivisbleUnicode == "FOO" # false
```

## REPL
```
» Str.toUtf8 "﻿FOO" 

[239, 187, 191, 70, 79, 79] : List U8

» Str.toUtf8 "\u(feff)FOO"

[239, 187, 191, 70, 79, 79] : List U8
```

## after formatting
```roc
module []

# this string has invisible unicode in it... let's have the formatter make this obvious
stringWithInivisbleUnicode = "\u(feff)FOO"

expect stringWithInivisbleUnicode == "FOO" # false, but now it's easier to see what is causing this issue. 
```

**Comment by a-lavis** [comment]
@lukewilliamboswell 

I started looking into this one and I think I have a solution:
https://github.com/roc-lang/roc/compare/main...a-lavis:roc:format-invisible-chars

However, there's one thing I'm not sure how to deal with - the formatter checks to make sure that the AST before formatting matches the AST after formatting:
https://github.com/roc-lang/roc/blob/d4d9f69d0fbefd331172c11e430a5f2ac98ee30b/crates/cli/src/format.rs#L205-L216

Consider this roc program:
```roc
app [main] {
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br",
}

import pf.Stdout

main =
    x = "foobar​"

    Stdout.line! x
```
With my changes it will format to:
```roc
app [main] {
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br",
}

import pf.Stdout

main =
    x = "foobar\u(200b)"

    Stdout.line! x
```
I believe this is the result we want.  However, these two files parse to different ASTs.  Here's the diff:
```diff
<                                     PlainLine(
<                                         "foobar\u{200b}",
---
>                                     Line(
>                                         [
>                                             Plaintext(
>                                                 "foobar",
>                                             ),
>                                             Unicode(
>                                                 "200b",
>                                             ),
>                                         ],
```

I can think of some unsatisfactory options:

1. Disable checking that the ASTs match when reformatting.
2. As the comment says, "fix PartialEq impl on ast types".  This seems out of scope for this particular issue - this comment seems to have been introduced by #2082, but I couldn't find a GitHub issue tracking it.  Also, I'm not sure if we necessarily want to consider these two ASTs as equal anyway.

I'm curious to hear your thoughts on the matter - maybe there's something else I'm missing here, since I'm new to contributing to roc :)

**Comment by joshuawarner32** [comment]
I think the right fix here is to update the RemoveSpaces impl (a bit mis-named, for how we actually use it!) to produce a maximally-normalized version of the string. In particular, it should merge all blocks / segments (that are not interpolations), apply all escapes, etc. So in this instance, it would normalize both to `StrLiteral(PlainLine("foobar\u{200b}"))`.

**Comment by joshuawarner32** [comment]
@a-lavis I have some time coming up where I could take a look at that, unless you want to. (alternatively, happy to provide more guidance if you're interested in diving more into the parser/formatter!)

**Comment by a-lavis** [comment]
@joshuawarner32 thanks so much for #6982!

I was busy the past two weeks but I just up a PR that should resolve this issue: #7004
