### ISSUE TITLE
Roc searches for .o instead of .a in built platform when used with --build-host

### ISSUE THREAD

**Issue by gree7** [roc-lang/roc#7271]
With a locally built `basic-webserver` platform, when I try to build against it a project (in my case the https://github.com/lukewilliamboswell/roc-htmx-playground/) Roc searches for `linux-x64.o` instead of `linux-x64.a`, which was built in the platform:
```
roc build --build-host --suppress-build-host-warning --linker=legacy src/main.roc
🔨 Building host ...
ld: cannot find src/../../basic-webserver/platform/linux-x64.o: No such file or directory
thread 'main' panicked at crates/compiler/build/src/program.rs:1058:17:
not yet implemented: linker failed with exit code Some(1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The built platform files:
```
$ ls platform/
Command.roc
Dir.roc
EnvDecoding.roc
Env.roc
FileMetadata.roc
File.roc
Http.roc
InternalCommand.roc
InternalDateTime.roc
InternalError.roc
InternalFile.roc
InternalHttp.roc
InternalPath.roc
InternalSQL.roc
InternalTcp.roc
libapp.roc
libapp.so
linux-x64.a
linux-x64.rh
main-glue.roc
main.roc
metadata_linux-x64.rm
MultipartFormData.roc
Path.roc
PlatformTasks.roc
Sleep.roc
SplitList.roc
SQLite3.roc
Stderr.roc
Stdout.roc
Tcp.roc
Url.roc
Utc.roc
```

Roc version:
`roc nightly pre-release, built from commit 8dbc909 on Fr 15 Nov 2024 09:02:07 UTC`

Related Zulip discussion: https://roc.zulipchat.com/#narrow/channel/231634-beginners/topic/client-side.20web.20in.20Roc/near/485096172

OS:
```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling
$ uname -a
Linux zephy 6.12.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:23 +0000 x86_64 GNU/Linux
```

**Comment by lukewilliamboswell** [comment]
The `--build-host` flag is for internal tests only and should not be used. The previous functionality for host rebuilding was removed in #6859, and some functionality retained behind this flag for the purpose of e2e testing internally.

The specific issue experienced here is caused by https://github.com/roc-lang/roc/blob/a9682517093f1e8cdd75572269e5acdcadbb45cf/crates/compiler/build/src/program.rs#L1095 I believe. 

I propose we close this issue as the functionality for this use case is not supported. 

I think `roc build --linker=legacy src/main.roc` (without the `--build-host` flag) should be working ok. Are you able to confirm this?

**Comment by gree7** [comment]
Confirmed. Without `--build-host` with the locally built platform it works fine.
